"""Add StudentUnitProgress and SegmentProgress models

Revision ID: 44552f7ef700
Revises: d98aa21b169b
Create Date: 2025-06-18 11:26:54.907488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44552f7ef700'
down_revision: Union[str, None] = 'd98aa21b169b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_unit_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_course_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_course_id'], ['student_courses.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_unit_progress_id'), 'student_unit_progress', ['id'], unique=False)
    op.create_table('segment_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_unit_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_unit_id'], ['student_unit_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_progress_id'), 'segment_progress', ['id'], unique=False)
    op.alter_column('student_courses', 'enrolled_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_courses', 'enrolled_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_segment_progress_id'), table_name='segment_progress')
    op.drop_table('segment_progress')
    op.drop_index(op.f('ix_student_unit_progress_id'), table_name='student_unit_progress')
    op.drop_table('student_unit_progress')
    # ### end Alembic commands ###
