"""Add StudentCourse model and remove user_courses table

Revision ID: d98aa21b169b
Revises: f44b4a297d63
Create Date: 2025-06-17 19:53:00.762945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98aa21b169b'
down_revision: Union[str, None] = 'f44b4a297d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_on', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('status', sa.String(), nullable=False, server_default='active'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_courses_id'), 'student_courses', ['id'], unique=False)
    op.drop_table('user_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_courses',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='user_courses_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_courses_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='user_courses_pkey')
    )
    op.drop_index(op.f('ix_student_courses_id'), table_name='student_courses')
    op.drop_table('student_courses')
    # ### end Alembic commands ###
